"""Initial schema, frozen at v0.1.0."""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_keys",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "key"),
    )
    op.create_table(
        "projects",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("target_duration_s", sa.Integer(), nullable=False),
        sa.Column("style", sa.String(), nullable=False),
        sa.Column("input_mode", sa.String(), nullable=False),
        sa.Column("constraints_json", sa.JSON(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("latest_analysis_id", sa.String(), nullable=True),
        sa.Column("demo_scenario", sa.String(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyses",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("project_revision", sa.Integer(), nullable=False),
        sa.Column("asset_snapshot", sa.JSON(), nullable=False),
        sa.Column("config_hash", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analyses_project_id"), "analyses", ["project_id"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("has_audio", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assets_project_id"), "assets", ["project_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("completed_units", sa.Integer(), nullable=False),
        sa.Column("total_units", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_table(
        "completion_plans",
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_completion_plans_analysis_id"),
        "completion_plans",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_completion_plans_project_id"),
        "completion_plans",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "edit_versions",
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("render_status", sa.String(), nullable=False),
        sa.Column("output_key", sa.String(), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edit_versions_project_id"),
        "edit_versions",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "evidence",
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_analysis_id"), "evidence", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_project_id"), "evidence", ["project_id"], unique=False
    )
    op.create_table(
        "gaps",
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gaps_analysis_id"), "gaps", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_gaps_project_id"), "gaps", ["project_id"], unique=False)
    op.create_table(
        "requirement_matches",
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirement_matches_analysis_id"),
        "requirement_matches",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirement_matches_project_id"),
        "requirement_matches",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "requirements",
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requirements_analysis_id"),
        "requirements",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirements_project_id"), "requirements", ["project_id"], unique=False
    )
    op.create_table(
        "shots",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shots_asset_id"), "shots", ["asset_id"], unique=False)
    op.create_index(op.f("ix_shots_project_id"), "shots", ["project_id"], unique=False)
    op.create_table(
        "transcript_segments",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcript_segments_asset_id"),
        "transcript_segments",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_segments_project_id"),
        "transcript_segments",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "completion_tasks",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["completion_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_completion_tasks_plan_id"),
        "completion_tasks",
        ["plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_completion_tasks_project_id"),
        "completion_tasks",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("verification_status", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["completion_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submissions_project_id"), "submissions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_submissions_task_id"), "submissions", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_task_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_project_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_completion_tasks_project_id"), table_name="completion_tasks")
    op.drop_index(op.f("ix_completion_tasks_plan_id"), table_name="completion_tasks")
    op.drop_table("completion_tasks")
    op.drop_index(
        op.f("ix_transcript_segments_project_id"), table_name="transcript_segments"
    )
    op.drop_index(
        op.f("ix_transcript_segments_asset_id"), table_name="transcript_segments"
    )
    op.drop_table("transcript_segments")
    op.drop_index(op.f("ix_shots_project_id"), table_name="shots")
    op.drop_index(op.f("ix_shots_asset_id"), table_name="shots")
    op.drop_table("shots")
    op.drop_index(op.f("ix_requirements_project_id"), table_name="requirements")
    op.drop_index(op.f("ix_requirements_analysis_id"), table_name="requirements")
    op.drop_table("requirements")
    op.drop_index(
        op.f("ix_requirement_matches_project_id"), table_name="requirement_matches"
    )
    op.drop_index(
        op.f("ix_requirement_matches_analysis_id"), table_name="requirement_matches"
    )
    op.drop_table("requirement_matches")
    op.drop_index(op.f("ix_gaps_project_id"), table_name="gaps")
    op.drop_index(op.f("ix_gaps_analysis_id"), table_name="gaps")
    op.drop_table("gaps")
    op.drop_index(op.f("ix_evidence_project_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_analysis_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_edit_versions_project_id"), table_name="edit_versions")
    op.drop_table("edit_versions")
    op.drop_index(op.f("ix_completion_plans_project_id"), table_name="completion_plans")
    op.drop_index(
        op.f("ix_completion_plans_analysis_id"), table_name="completion_plans"
    )
    op.drop_table("completion_plans")
    op.drop_index(op.f("ix_jobs_project_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_assets_project_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_analyses_project_id"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_table("projects")
    op.drop_table("idempotency_keys")
    # ### end Alembic commands ###
